query getStrapiData {
  works {
    orderId
    companyTitle
    slug
    industry
    media
    roles
    project {
      id
      projectTitle
      projectSummary
      projectImg {
        url
      }
      designTools
      codingTools
    }
  }
}